# Generated by Django 5.1.7 on 2025-03-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('edition_type', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('acquisition_method', models.CharField(choices=[('purchase', 'Purchased'), ('donation', 'Donated'), ('other', 'Other')], max_length=20)),
                ('publisher', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='book_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarySystem.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarySystem.reader')),
            ],
        ),
    ]
